BudgetPlannerMVC.Web/Controllers/AmountController.cs
using BudgetPlannerMVC.Application.Interfaces;
using BudgetPlannerMVC.Application.ViewModels.AmountView;
using BudgetPlannerMVC.Application.ViewModels.TypeView;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;

namespace BudgetPlannerMVC.Web.Controllers
{
    [Authorize]
    public class AmountController : Controller
    {
        private readonly IAmountService _amountService;
        private readonly ITypeService _typeService;
        private readonly IBudgetUserService _budgetUserService;
        private readonly IUserRoleService _userRoleService;
        public AmountController(IAmountService amountService, ITypeService typeService, IBudgetUserService budgetUserService, IUserRoleService userRoleService)
        {
            _amountService = amountService;
            _typeService = typeService;
            _budgetUserService = budgetUserService;
            _userRoleService = userRoleService; 
        }
        [HttpGet]
        [Authorize(Roles = "Admin, User")]
        public IActionResult Index()
        {
            DateTime startDate = new DateTime(year: DateTime.Now.Year, month: DateTime.Now.Month, day: 1);
            DateTime endDate = new DateTime(year: DateTime.Now.Year, month: DateTime.Now.Month, day: DateTime.Now.Day, hour:23, minute: 59, second:59, millisecond:999);
            var budgetUsers = _budgetUserService.DropDownBudgetUsers();
            var types = _typeService.DropDownTypes();
            FilterForAmountForListAmount filterForAmount = new FilterForAmountForListAmount()
            {
                SearchTypeId = 0,
                SearchUserId = 0,
                BudgetUsers = budgetUsers,
                Types = types
            };
            var dateSelect = _amountService.GetDateSelect(startDate, endDate); 
            var amounts = _amountService.GetFiltredAmountsForList(filterForAmount, dateSelect);
            var sumValues = _amountService.GetSumValuesForListAmount(amounts);
            var typeUserName = _amountService.SelectedUserNameForListAmount(filterForAmount);
            var model = _amountService.GetAllAmountsForList(6, 1, sumValues, typeUserName, amounts, dateSelect);
            model.FilterForAmount = filterForAmount;
            return View(model);
        }
        [HttpPost]
        [Authorize(Roles = "Admin, User")]
        public IActionResult Index(int pageSize, int? pageNo, FilterForAmountForListAmount filterForAmount, DateSelectForListAmountVm dateSelect)
        {
            if (!pageNo.HasValue)
            {
                pageNo = 1;
            }
            filterForAmount.BudgetUsers = _budgetUserService.DropDownBudgetUsers();
            filterForAmount.Types = _typeService.DropDownTypes();
            var amounts = _amountService.GetFiltredAmountsForList(filterForAmount, dateSelect);
            var sumValues = _amountService.GetSumValuesForListAmount(amounts);
            var typeUserName = _amountService.SelectedUserNameForListAmount(filterForAmount);
            var model = _amountService.GetAllAmountsForList(pageSize, pageNo.Value, sumValues, typeUserName, amounts, dateSelect);
            model.FilterForAmount = filterForAmount;
            return View(model);
        }
        [HttpGet]
        [Authorize(Roles = "Admin, User")]
        public IActionResult AddAmount()
        {
            var types = _typeService.DropDownTypes();
            var budgetUsers = _budgetUserService.DropDownBudgetUsers();
            var currentUserId = _userRoleService.GetCurrentUserId();
            var budgetUserId = _budgetUserService.GetBudgetUserIdLoggedIn(currentUserId);
            var model = new NewAmountVm()
            {
                Types = types,
                BudgetUsers = budgetUsers,
                BudgetUserId = budgetUserId
            };
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, User")]
        public IActionResult AddAmount(NewAmountVm model)
        {
            if (ModelState.IsValid)
            {
                var id = _amountService.AddAmount(model);
                return RedirectToAction("Index");
            }
            model.Types = _typeService.DropDownTypes();
            model.BudgetUsers = _budgetUserService.DropDownBudgetUsers();
            return View(model);
        }
        [HttpGet]
        [Authorize(Roles = "Admin, User")]
        public IActionResult EditAmount(int id)
        {
            var amount = _amountService.GetAmountForEdit(id);
            amount.Types = _typeService.DropDownTypes();
            amount.BudgetUsers = _budgetUserService.DropDownBudgetUsers();
            return View(amount);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, User")]
        public IActionResult EditAmount(NewAmountVm model)
        {
            if (ModelState.IsValid)
            {
                _amountService.UpdateAmount(model);
                return RedirectToAction("Index");
            }
            model.Types = _typeService.DropDownTypes();
            model.BudgetUsers = _budgetUserService.DropDownBudgetUsers();
            return View(model);
        }
        [HttpGet]
        [Authorize(Roles = "Admin, User")]
        public IActionResult Delete(int id)
        {
            var amount = _amountService.GetAmountForEdit(id);
            return View(amount);
        }
        [HttpPost]
        [Authorize(Roles = "Admin, User")]
        public IActionResult Delete(NewAmountVm model)
        {
            _amountService.DeleteAmount(model.Id);
            return RedirectToAction("Index");
        }
        [HttpGet]
        [Authorize(Roles = "Admin, User")]
        public IActionResult Details(int id)
        {
            var amount = _amountService.GetAmountForEdit(id);
            return View(amount);
        }
    }
}

BudgetPlannerMVC.Web/Controllers/BudgetStatusController.cs
using BudgetPlannerMVC.Application.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BudgetPlannerMVC.Web.Controllers
{
    [Authorize]
    public class BudgetStatusController : Controller
    {
        private readonly IBudgetStatusService _budgetStatusService;
        public BudgetStatusController(IBudgetStatusService budgetStatusService)
        {
            _budgetStatusService = budgetStatusService;
        }
        [Authorize(Roles = "Admin, User")]
        public IActionResult Index()
        {
            var plan = _budgetStatusService.GetActivePlanToBudgetStatusVm();    
            var planTypes = _budgetStatusService.GetPlanTypesOfPlanForBudgetStatusVm(plan);
            var amounts = _budgetStatusService.GetAmountsOutOfPlan(plan, planTypes);
            var sumValues = _budgetStatusService.GetSumValuesForBudgetStatusVm(planTypes, amounts);
            var model = _budgetStatusService.GetBudgetStatusForVm(planTypes, sumValues, plan);
            return View(model);
        }
    }
}

BudgetPlannerMVC.Web/Controllers/PlanController.cs
using BudgetPlannerMVC.Application.Interfaces;
using BudgetPlannerMVC.Application.ViewModels.PlanView;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;

namespace BudgetPlannerMVC.Web.Controllers
{
    [Authorize]
    public class PlanController : Controller
    {
        private readonly IPlanService _planService;
        public PlanController(IPlanService planService)
        {
            _planService = planService;
        }
        [HttpGet]
        [Authorize(Roles = "Admin, User")]
        public IActionResult Index()
        {
            var model = _planService.GetAllPlansForList(8, 1, "");
            return View(model);
        }
        [HttpPost]
        [Authorize(Roles = "Admin, User")]
        public IActionResult Index(int pageSize, int? pageNo, string searchString)
        {
            if (!pageNo.HasValue)
            {
                pageNo = 1;
            }
            if (searchString is null)
            {
                searchString = String.Empty;
            }
            var model = _planService.GetAllPlansForList(pageSize, pageNo.Value, searchString);
            return View(model);
        }
        [HttpGet]
        [Authorize(Roles = "Admin, User")]
        public IActionResult AddPlan()
        {
            return View(new NewPlanVm());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, User")]
        public IActionResult AddPlan(NewPlanVm model)
        {
            if (ModelState.IsValid)
            {
                var id = _planService.AddPlan(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }
        [HttpGet]
        [Authorize(Roles = "Admin, User")]
        public IActionResult EditPlan(int id)
        {
            var plan = _planService.GetPlanForEdit(id);
            return View(plan);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, User")]
        public IActionResult EditPlan(NewPlanVm model)
        {
            if (ModelState.IsValid)
            {
                _planService.UpdatePlan(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }
        [HttpGet]
        [Authorize(Roles = "Admin, User")]
        public IActionResult Delete(int id)
        {
            var plan = _planService.GetPlanForEdit(id);
            return View(plan);
        }
        [HttpPost]
        [Authorize(Roles = "Admin, User")]
        public IActionResult Delete(NewPlanVm model)
        {
            _planService.DeletePlan(model.Id);
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Admin, User")]
        public IActionResult Status(int id)
        {
            var plans = _planService.StatusPlan(id);
            _planService.UpdateListOfPlans(plans);
            return RedirectToAction("Index");
        }
    }
}

BudgetPlannerMVC.Web/Controllers/TypeController.cs
using BudgetPlannerMVC.Application.Interfaces;
using BudgetPlannerMVC.Application.ViewModels.TypeView;
using BudgetPlannerMVC.Domain.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;

namespace BudgetPlannerMVC.Web.Controllers
{
    [Authorize]
    public class TypeController : Controller
    {
        private readonly ITypeService _typeService;

        public TypeController(ITypeService typeService)
        {
            _typeService = typeService;
        }

        [HttpGet]
        [Authorize(Roles = "Admin, User")]
        public IActionResult Index()
        {
            var model = _typeService.GetAllTypesForList(8, 1, "");
            return View(model);
        }
        [HttpPost]
        [Authorize(Roles = "Admin, User")]
        public IActionResult Index(int pageSize, int? pageNo, string searchString)
        {
            if (!pageNo.HasValue)
            {
                pageNo = 1;
            }
            if (searchString is null)
            {
                searchString = String.Empty;
            }
            var model = _typeService.GetAllTypesForList(pageSize, pageNo.Value, searchString);
            return View(model);
        }

        [HttpGet]
        [Authorize(Roles = "Admin, User")]
        public IActionResult AddType()
        {
            var assigns = _typeService.DropDownAssigns();
            var model = new NewTypeVm()
            {
                Assigns = assigns
            };
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, User")]
        public IActionResult AddType(NewTypeVm model)
        {
            if (ModelState.IsValid)
            {
                var id = _typeService.AddType(model);
                return RedirectToAction("Index");
            }
            model.Assigns = _typeService.DropDownAssigns();
            return View(model);
        }
        [HttpGet]
        [Authorize(Roles = "Admin, User")]
        public IActionResult EditType(int id)
        {
            var type = _typeService.GetTypeForEdit(id);
            type.Assigns = _typeService.DropDownAssigns();
            return View(type);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, User")]
        public IActionResult EditType(NewTypeVm model)
        {
            if (ModelState.IsValid)
            {
                _typeService.UpdateType(model);
                return RedirectToAction("Index");
            }
            model.Assigns = _typeService.DropDownAssigns();
            return View(model);
        }
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            var type = _typeService.GetTypeForEdit(id);
            return View(type);
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(NewTypeVm model)
        {
            _typeService.DeleteType(model.Id);
            return RedirectToAction("Index");
        }
        [HttpGet]
        [Authorize(Roles = "Admin, User")]
        public IActionResult Details(int id)
        {
            var type = _typeService.GetTypeForEdit(id);
            return View(type);
        }
    }
}

BudgetPlannerMVC.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BudgetPlannerMVC Application</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="bg-light">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-info border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-dark font-weight-bold" asp-area="" asp-controller="Home" asp-action="Index">BudgetPlannerMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="BudgetStatus" asp-action="Index">Budget Status</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Amount" asp-action="Index">Amounts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Type" asp-action="Index">Budget Configuration</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Plan" asp-action="Index">Plan</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="BudgetUser" asp-action="Index">Budget Users</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BudgetPlannerMVC.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @* For DatePicker *@
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>

    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>