BudgetPlannerMVC.Web/Controllers/PlanController.cs
using BudgetPlannerMVC.Application.Interfaces;
using BudgetPlannerMVC.Application.ViewModels.PlanView;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;

namespace BudgetPlannerMVC.Web.Controllers
{
    [Authorize]
    public class PlanController : Controller
    {
        private readonly IPlanService _planService;
        public PlanController(IPlanService planService)
        {
            _planService = planService;
        }
        [HttpGet]
        [Authorize(Roles = "Admin, User")]
        public IActionResult Index()
        {
            var model = _planService.GetAllPlansForList(8, 1, "");
            return View(model);
        }
        [HttpPost]
        [Authorize(Roles = "Admin, User")]
        public IActionResult Index(int pageSize, int? pageNo, string searchString)
        {
            if (!pageNo.HasValue)
            {
                pageNo = 1;
            }
            if (searchString is null)
            {
                searchString = String.Empty;
            }
            var model = _planService.GetAllPlansForList(pageSize, pageNo.Value, searchString);
            return View(model);
        }
        [HttpGet]
        [Authorize(Roles = "Admin, User")]
        public IActionResult AddPlan()
        {
            return View(new NewPlanVm());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, User")]
        public IActionResult AddPlan(NewPlanVm model)
        {
            if (ModelState.IsValid)
            {
                var id = _planService.AddPlan(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }
        [HttpGet]
        [Authorize(Roles = "Admin, User")]
        public IActionResult EditPlan(int id)
        {
            var plan = _planService.GetPlanForEdit(id);
            return View(plan);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, User")]
        public IActionResult EditPlan(NewPlanVm model)
        {
            if (ModelState.IsValid)
            {
                _planService.UpdatePlan(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }
        [HttpGet]
        [Authorize(Roles = "Admin, User")]
        public IActionResult Delete(int id)
        {
            var plan = _planService.GetPlanForEdit(id);
            return View(plan);
        }
        [HttpPost]
        [Authorize(Roles = "Admin, User")]
        public IActionResult Delete(NewPlanVm model)
        {
            _planService.DeletePlan(model.Id);
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Admin, User")]
        public IActionResult Status(int id)
        {
            var plans = _planService.StatusPlan(id);
            _planService.UpdateListOfPlans(plans);
            return RedirectToAction("Index");
        }
    }
}

BudgetPlannerMVC.Web/Controllers/PlanTypeController.cs
using BudgetPlannerMVC.Application.Interfaces;
using BudgetPlannerMVC.Application.ViewModels.PlanView;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BudgetPlannerMVC.Web.Controllers
{
    [Authorize]
    public class PlanTypeController : Controller
    {
        private readonly IPlanTypeService _planTypeService;

        public PlanTypeController(IPlanTypeService planTypeService)
        {
            _planTypeService = planTypeService;
        }
        [HttpGet]
        [Authorize(Roles = "Admin, User")]
        public IActionResult Index(int id)
        {
            var model = _planTypeService.GetAllPlanTypesForList(8, 1, "", id);
            return View(model);
        }
        [HttpPost]
        [Authorize(Roles = "Admin, User")]
        public IActionResult Index(int pageSize, int? pageNo, string searchString, int id)
        {
            if (!pageNo.HasValue)
            {
                pageNo = 1;
            }
            if (searchString is null)
            {
                searchString = String.Empty;
            }
            var model = _planTypeService.GetAllPlanTypesForList(pageSize, pageNo.Value, searchString, id);
            return View(model);
        }
        [HttpGet]
        [Authorize(Roles = "Admin, User")]
        public IActionResult AddPlanType(int id)
        {
            var planTypes = _planTypeService.DropDownTypesForPlan(id);
            var model = new NewPlanTypeVm() {
                PlanId = id,
                PlanTypes = planTypes
            };
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, User")]
        public IActionResult AddPlanType(NewPlanTypeVm model, int id)
        {
            if (ModelState.IsValid)
            {
                var planTypeId = _planTypeService.AddPlanType(model);
                return RedirectToAction("Index", new { id });
            }
            model.PlanTypes = _planTypeService.DropDownTypesForPlan(id);
            return View(model);
        }
        [HttpGet]
        [Authorize(Roles = "Admin, User")]
        public IActionResult EditPlanType(int id)
        {
            var planType = _planTypeService.GetPlanTypeForEdit(id);
            return View(planType);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, User")]
        public IActionResult EditPlanType(NewPlanTypeVm model)
        {
            if (ModelState.IsValid)
            {
                _planTypeService.UpdatePlanType(model);
                return RedirectToAction("Index", new { id = model.PlanId });
            }
            return View(model);
        }
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            var planType = _planTypeService.GetPlanTypeForEdit(id);
            return View(planType);
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(NewPlanTypeVm model)
        {
            var planId = _planTypeService.DeletePlanType(model.Id);
            return RedirectToAction("Index", new {id = planId});
        }
    }
}

BudgetPlannerMVC.Web/Views/PlanType/AddPlanType.cshtml
@model BudgetPlannerMVC.Application.ViewModels.PlanView.NewPlanTypeVm

@{
    ViewData["Title"] = "AddPlanType";
}

<h1 class="display-4">Add Type to Plan</h1>

<hr />
<div class="row" style="margin-bottom:60px">
    <div class="col-md-4">
        <form asp-action="AddPlanType">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="hidden" asp-for="Id" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Value" class="control-label"></label>
                <input asp-for="Value" class="form-control" />
                <span asp-validation-for="Value" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Type of Amount</label>
                @Html.DropDownListFor(model => model.TypeId, new SelectList(Model.PlanTypes, "Id", "NameAndAssign"), new { @class = "form-control btn btn-outline-dark dropdown-toggle" })
                <span asp-validation-for="TypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="PlanId" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                <a class="btn btn-dark" asp-action="Index" asp-route-id="@Model.PlanId">Back to Types</a>
            </div>
        </form>
    </div>
</div>

BudgetPlannerMVC.Web/Views/PlanType/Delete.cshtml
@model BudgetPlannerMVC.Application.ViewModels.PlanView.NewPlanTypeVm

@{
    ViewData["Title"] = "Delete";
}

<h1 class="display-4">Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div style="margin-bottom:60px">
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Type.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Type.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Value)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Value)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a class="btn btn-dark" asp-action="Index" asp-route-id="@Model.PlanId">Back to Types</a>
    </form>
</div>

BudgetPlannerMVC.Web/Views/PlanType/EditPlanType.cshtml
@model BudgetPlannerMVC.Application.ViewModels.PlanView.NewPlanTypeVm

@{
    ViewData["Title"] = "EditPlanType";
}

<h1 class="display-4">Edit PlanType</h1>
<div class="font-weight-bold">
    @Html.DisplayFor(model => model.Type.Name)
</div>

<hr />
<div class="row" style="margin-bottom:60px">
    <div class="col-md-4">
        <form asp-action="EditPlanType">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="hidden" asp-for="Id" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Value" class="control-label"></label>
                <input asp-for="Value" class="form-control" />
                <span asp-validation-for="Value" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="TypeId" class="form-control" />
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="PlanId" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a class="btn btn-dark" asp-action="Index" asp-route-id="@Model.PlanId">Back to Types</a>
            </div>
        </form>
    </div>
</div>

BudgetPlannerMVC.Web/Views/PlanType/Index.cshtml
@model BudgetPlannerMVC.Application.ViewModels.PlanView.ListPlanTypesForListVm

@{
    ViewData["Title"] = "Index";
}

<h1 class="display-4">@Model.PlanName</h1>

<p>
    <a class="btn btn-primary" asp-action="AddPlanType" asp-route-id="@Model.PlanId">Add Type to Plan</a>
</p>
<form asp-action="Index" asp-controller="PlanType" method="post" style="margin-bottom:60px">
    <div class="form-inline justify-content-start">
        <div class="d-flex" style="margin:10px 20px 20px 0px">
            <div class="d-flex">
                <input class="form-control form-rounded" type="text" asp-for="SearchString" name="searchString" id="searchString" placeholder="Search" />
            </div>
            <div class="d-flex">
                <input class="btn btn-outline-dark ml-2" type="submit" value="Search" />
            </div>
        </div>
    </div>
    <div class="row">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Name
                    </th>
                    <th>
                        Assignment
                    </th>
                    <th>
                        Planned Value
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.PlanTypes)
                {
                    <tr>
                        @if (item.Type.AssignId == 1)
                        {
                            <td class="text-danger">
                                @Html.DisplayFor(modelItem => item.Type.Name)
                            </td>
                            <td class="text-danger">
                                @Html.DisplayFor(modelItem => item.Type.Assign.Name)
                            </td>
                            <td class="text-danger">
                                @Html.DisplayFor(modelItem => item.Value)
                            </td>
                        }
                        else
                        {
                            <td class="text-success">
                                @Html.DisplayFor(modelItem => item.Type.Name)
                            </td>
                            <td class="text-success">
                                @Html.DisplayFor(modelItem => item.Type.Assign.Name)
                            </td>
                            <td class="text-success">
                                @Html.DisplayFor(modelItem => item.Value)
                            </td>
                        }
                        <td>
                            @Html.ActionLink("Edit", "EditPlanType", new { id=item.Id }, new { @class = "btn btn-info" })
                            @Html.ActionLink("Delete", "Delete", new { id=item.Id }, new { @class = "btn btn-danger" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="row">
        <table>
            <tr>
                @for (int i = 1; i <= Math.Ceiling(Model.Count / (double)Model.PageSize); i++)
                {
                    <td>

                        @if (i != Model.CurrentPage)
                        {
                            <a class="badge badge-dark" href="javascript:PagerClick(@i)">@i</a>
                        }
                        else
                        {
                            <span class="badge badge-outline-dark">@i</span>
                        }
                    </td>
                }
            </tr>
        </table>
        <input type="hidden" name="pageNo" id="pageNo" />
        <input type="hidden" name="pageSize" id="pageSize" value="8" />
    </div>
    <div>
        <a class="btn btn-dark" asp-controller="Plan" asp-action="Index">Back to Plans</a>
    </div>
</form>
@section Scripts
{
<script type="text/javascript">
    function PagerClick(index)
    {
        document.getElementById("pageNo").value = index;
        document.forms[1].submit();
    }
</script>
}