BudgetPlannerMVC.Web/Controllers/BudgetUserController.cs
using BudgetPlannerMVC.Application.Interfaces;
using BudgetPlannerMVC.Application.ViewModels.BudgetUserView;
using BudgetPlannerMVC.Application.ViewModels.UserRoleView;
using BudgetPlannerMVC.Infrastructure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace BudgetPlannerMVC.Web.Controllers
{
    [Authorize]
    public class BudgetUserController : Controller
    {
        private readonly IBudgetUserService _budgetUserService;
        private readonly IUserRoleService _userRoleService;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly UserManager<IdentityUser> _userManager;
        public BudgetUserController(IBudgetUserService budgetUserService, 
            IUserRoleService userRoleService, 
            SignInManager<IdentityUser> signInManager,
            UserManager<IdentityUser> userManager)
        {
            _budgetUserService = budgetUserService;
            _userRoleService = userRoleService;
            _signInManager = signInManager;
            _userManager = userManager;
        }
        [HttpGet]
        [Authorize(Roles = "Admin, User, PreUser")]
        public IActionResult Index()
        {
            var model = _budgetUserService.GetAllBudgetUsersForList(8, 1, "");
            var currentUserId = _userRoleService.GetCurrentUserId();
            model.CurrentUserId = currentUserId;
            return View(model);
        }
        [HttpPost]
        [Authorize(Roles = "Admin, User, PreUser")]
        public IActionResult Index(int pageSize, int? pageNo, string searchString)
        {
            if (!pageNo.HasValue)
            {
                pageNo = 1;
            }
            if (searchString is null)
            {
                searchString = String.Empty;
            }
            var model = _budgetUserService.GetAllBudgetUsersForList(pageSize, pageNo.Value, searchString);
            var currentUserId = _userRoleService.GetCurrentUserId();
            model.CurrentUserId = currentUserId;
            return View(model);
        }
        [HttpGet]
        [Authorize(Roles = "PreUser")]
        public IActionResult CreateBudgetUserProfile()
        {
            var userId = _userRoleService.GetCurrentUserId();
            var model = _budgetUserService.GetBudgetUserForCreateProfile(userId);
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "PreUser")]
        public async Task<IActionResult> CreateBudgetUserProfileAsync(NewBudgetUserVm model, string addContact, string removeContact)
        {
            if (ModelState.IsValid && addContact == null && removeContact == null)
            {
                _budgetUserService.UpdateBudgetUser(model);
                _userRoleService.UpdateUserRole(model.UserId);
                await _signInManager.SignOutAsync();
                return RedirectToAction("Index");
            }
            var allContactTypes = _budgetUserService.CountContactDetailsForAddBudgetUser(model, addContact, removeContact);
            model.CountContactDetailsType = allContactTypes;
            model.ContactDetailTypes = _budgetUserService.DropDownContactDetailTypes();
            return View(model);
        }
        [HttpGet]
        [Authorize(Roles = "Admin, User")]
        public IActionResult EditBudgetUser(int id)
        {
            var budgetUser = _budgetUserService.GetBudgetUserForEdit(id);
            budgetUser.ContactDetailTypes = _budgetUserService.DropDownContactDetailTypes();
            budgetUser.CountContactDetailsType = budgetUser.ContactDetails.Count - 1;
            var currentUserId = _userRoleService.GetCurrentUserId();
            if (User.IsInRole("User") && budgetUser.UserId != currentUserId)
            {
                return RedirectToAction("Index");
            }
            return View(budgetUser);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, User")]
        public IActionResult EditBudgetUser(NewBudgetUserVm model, string addContact, string removeContact)
        {
            var currentUserId = _userRoleService.GetCurrentUserId();
            if (ModelState.IsValid && addContact == null && removeContact == null)
            {
                if (User.IsInRole("Admin") || (User.IsInRole("User") && model.UserId == currentUserId))
                {
                    _budgetUserService.UpdateBudgetUser(model);
                }
                return RedirectToAction("Index");
            }
            var allContactTypes = _budgetUserService.CountContactDetailsForAddBudgetUser(model, addContact, removeContact);
            model.CountContactDetailsType = allContactTypes;

            model.ContactDetailTypes = _budgetUserService.DropDownContactDetailTypes();
            return View(model);
        }
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            var budgetUser = _budgetUserService.GetBudgetUserForEdit(id);
            var roleId = _userRoleService.GetUserRoleIdByUserId(budgetUser.UserId);
            if (roleId == "Admin")
            {
                return RedirectToAction("Index");
            }
            return View(budgetUser);
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteAsync(int id)
        {
            var budgetUser = _budgetUserService.GetBudgetUserForEdit(id);
            var user = await _userManager.FindByIdAsync(budgetUser.UserId);
            var result = await _userManager.DeleteAsync(user);
            if (result.Succeeded)
            {
                _budgetUserService.DeleteBudgetUser(id);
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        [Authorize(Roles = "Admin, User, PreUser")]
        public IActionResult Details(int id)
        {
            var budgetUser = _budgetUserService.GetBudgetUserForEdit(id);
            return View(budgetUser);
        }
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult EditUserRole(string userId)
        {
            var userModel = _userRoleService.GetUserForEditRoleByUserId(userId);
            var userLoggedIn = _userRoleService.GetCurrentUserId();
            if (userLoggedIn == userId && userModel.CountAdminRole <= 1)
            {
                return RedirectToAction("Index");
            }
            return View(userModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> EditUserRoleAsync(EditUserRoleVm editUserRoleVm)
        {
            _userRoleService.UpdateUserRole(editUserRoleVm.UserId, editUserRoleVm.UserRoleId);
            if (editUserRoleVm.UserRoleId == "Admin")
            {
                await _signInManager.SignOutAsync();
            }
            return RedirectToAction("Index");
        }
    }
}

BudgetPlannerMVC.Web/Views/BudgetUser/AddBudgetUser.cshtml
@using BudgetPlannerMVC.Application.ViewModels.BudgetUserView
@model BudgetPlannerMVC.Application.ViewModels.BudgetUserView.NewBudgetUserVm

@{
    ViewData["Title"] = "AddBudgetUser";
}

<h1 class="display-4">Add Budget User</h1>

<hr />
<div class="row" style="margin-bottom:60px">
    <div class="col-md-4">
        <form asp-action="AddBudgetUser">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="hidden" asp-for="Id" class="form-control" />
            </div>
            <div class="form-group">
                <label class="control-label">First Name</label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Last Name</label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>

            @for (int i = 0; i <= @Model.CountContactDetailsType; i++)
            {
                string valueContactType = $"Contact Type {i + 1}";
                <div class="form-group">
                    <label class="control-label">@valueContactType</label>
                    @Html.DropDownListFor(model => model.ContactDetails[i].ContactDetailTypeId, new SelectList(Model.ContactDetailTypes, "Id", "Name"), new { @class = "form-control btn btn-outline-dark dropdown-toggle" })
                    <input asp-for="ContactDetails[i].ContactDetailInformation" class="form-control" placeholder="Write contact information" style="margin-top: 20px" />
                    <span asp-validation-for="ContactDetails[i].ContactDetailInformation" class="text-danger"></span>
                </div>
            }
            <div class="form-group">
                <input type="hidden" asp-for="CountContactDetailsType" class="form-control" id="countContactType" value="@Model.CountContactDetailsType">
                <input asp-action="AddBudgetUser" type="submit" class="btn btn-info" name="addContact" value="Add Contact" />
                @if (@Model.CountContactDetailsType != 0)
                {
                    <input asp-action="AddBudgetUser" type="submit" class="btn btn-warning" name="removeContact" value="Remove Contact" />
                }
            </div>
            <div class="form-group">
                <label asp-for="Address.Street" class="control-label"></label>
                <input asp-for="Address.Street" class="form-control" />
                <span asp-validation-for="Address.Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Building Number</label>
                <input asp-for="Address.BuildingNumber" class="form-control" />
                <span asp-validation-for="Address.BuildingNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Flat Number</label>
                <input asp-for="Address.FlatNumber" class="form-control" />
                <span asp-validation-for="Address.FlatNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Zip Code</label>
                <input asp-for="Address.ZipCode" class="form-control" />
                <span asp-validation-for="Address.ZipCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.City" class="control-label"></label>
                <input asp-for="Address.City" class="form-control" />
                <span asp-validation-for="Address.City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.Country" class="control-label"></label>
                <input asp-for="Address.Country" class="form-control" />
                <span asp-validation-for="Address.Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                <a class="btn btn-dark" asp-action="Index">Back to Budget Users</a>
            </div>
        </form>
    </div>
</div>

BudgetPlannerMVC.Web/Views/BudgetUser/CreateBudgetUserProfile.cshtml
@using BudgetPlannerMVC.Application.ViewModels.BudgetUserView
@model BudgetPlannerMVC.Application.ViewModels.BudgetUserView.NewBudgetUserVm

@{
    ViewData["Title"] = "CreateBudgetUserProfile";
}

<h1 class="display-4">Create Profile</h1>

<hr />
<div class="row" style="margin-bottom:60px">
    <div class="col-md-4">
        <form asp-action="CreateBudgetUserProfile">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="hidden" asp-for="Id" class="form-control" />
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="UserId" class="form-control" />
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="UserName" class="form-control" />
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="MainMail" class="form-control" />
            </div>
            <div class="form-group">
                <label class="control-label">User Name</label>
                <input asp-for="UserName" class="form-control", disabled="disabled" />
            </div>
            <div class="form-group">
                <label class="control-label">First Name</label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Last Name</label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>

            @for (int i = 0; i <= @Model.CountContactDetailsType; i++)
            {
                string valueContactType = $"Contact Type {i + 1}";
                <div class="form-group">
                    <label class="control-label">@valueContactType</label>
                    @Html.DropDownListFor(model => model.ContactDetails[i].ContactDetailTypeId, new SelectList(Model.ContactDetailTypes, "Id", "Name"), new { @class = "form-control btn btn-outline-dark dropdown-toggle" })
                    <input asp-for="ContactDetails[i].ContactDetailInformation" class="form-control" placeholder="Write contact information" style="margin-top: 20px" />
                    <span asp-validation-for="ContactDetails[i].ContactDetailInformation" class="text-danger"></span>
                </div>
            }
            <div class="form-group">
                <input type="hidden" asp-for="CountContactDetailsType" class="form-control" id="countContactType" value="@Model.CountContactDetailsType">
                <input asp-action="CreateBudgetUserProfile" type="submit" class="btn btn-info" name="addContact" value="Add Contact" />
                @if (@Model.CountContactDetailsType != 0)
                {
                    <input asp-action="CreateBudgetUserProfile" type="submit" class="btn btn-warning" name="removeContact" value="Remove Contact" />
                }
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="Address.Id" class="form-control" />
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="Address.BudgetUserId" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Address.Street" class="control-label"></label>
                <input asp-for="Address.Street" class="form-control" />
                <span asp-validation-for="Address.Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Building Number</label>
                <input asp-for="Address.BuildingNumber" class="form-control" />
                <span asp-validation-for="Address.BuildingNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Flat Number</label>
                <input asp-for="Address.FlatNumber" class="form-control" />
                <span asp-validation-for="Address.FlatNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Zip Code</label>
                <input asp-for="Address.ZipCode" class="form-control" />
                <span asp-validation-for="Address.ZipCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.City" class="control-label"></label>
                <input asp-for="Address.City" class="form-control" />
                <span asp-validation-for="Address.City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.Country" class="control-label"></label>
                <input asp-for="Address.Country" class="form-control" />
                <span asp-validation-for="Address.Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                <a class="btn btn-dark" asp-action="Index">Back to Budget Users</a>
            </div>
        </form>
    </div>
</div>

BudgetPlannerMVC.Web/Views/BudgetUser/Delete.cshtml
@model BudgetPlannerMVC.Application.ViewModels.BudgetUserView.NewBudgetUserVm

@{
    ViewData["Title"] = "Delete";
}

<h1 class="display-4">Delete Budget User</h1>

<h3>Are you sure you want to delete this?</h3>
<div style="margin-bottom:60px">
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            User Name
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class="col-sm-2">
            First Name
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            Last Name
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a class="btn btn-dark" asp-action="Index">Back to Budget Users</a>
    </form>
</div>

BudgetPlannerMVC.Web/Views/BudgetUser/Details.cshtml
@model BudgetPlannerMVC.Application.ViewModels.BudgetUserView.NewBudgetUserVm

@{
    ViewData["Title"] = "Details";
}

<h1 class="display-4">Details</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            User Name
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class="col-sm-2">
            First Name
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            Last Name
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        @{
            var i = 1;
            var j = 1;
        }
        @foreach (var item in Model.ContactDetails)
        {
            if (item.ContactDetailTypeId == 1)
            {
                <dt class="col-sm-2">
                    Mail address @i
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(modelItem => item.ContactDetailInformation)
                </dd>
                i++;
            }
            else if (item.ContactDetailTypeId == 2)
            {
                <dt class="col-sm-2">
                    Phone number @j
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(modelItem => item.ContactDetailInformation)
                </dd>
                j++;
            }
            else
            {
                <dt class="col-sm-2">
                    Contact
                </dt>
                <dd class="col-sm-10">
                    No contact
                </dd>
            }
        }
        @foreach (var item in Model.Addresses)
        {
            <dt class="col-sm-2">
                @Html.DisplayNameFor(modelItem => item.Street)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(modelItem => item.Street)
            </dd>
            <dt class="col-sm-2">
                Building Number
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(modelItem => item.BuildingNumber)
            </dd>
            <dt class="col-sm-2">
                Flat Number
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(modelItem => item.FlatNumber)
            </dd>
            <dt class="col-sm-2">
                Zip Code
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(modelItem => item.ZipCode)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(modelItem => item.City)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(modelItem => item.City)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(modelItem => item.Country)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(modelItem => item.Country)
            </dd>
        }
    </dl>
</div>
<div style="margin-bottom:60px">
    @Html.ActionLink("Edit", "EditBudgetUser", new { id = Model.Id }, new { @class = "btn btn-info" })
    <a class="btn btn-dark" asp-action="Index">Back to Budget Users</a>
</div>

BudgetPlannerMVC.Web/Views/BudgetUser/EditUserRole.cshtml
@model BudgetPlannerMVC.Application.ViewModels.UserRoleView.EditUserRoleVm

@{
    ViewData["Title"] = "EditUserRole";
}

<h1>Edit User Role</h1>

<hr />
<div class="row" style="margin-bottom:60px">
    <div class="col-md-4">
        <form asp-action="EditUserRole">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">User Name</label>
                <input asp-for="UserName" class="form-control", disabled="disabled"/>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="Id" class="form-control" />
            </div>
            <div class="form-group">
                <label class="control-label">First Name</label>
                <input asp-for="FirstName" class="form-control", disabled="disabled"/>
            </div>
            <div class="form-group">
                <label class="control-label">Last Name</label>
                <input asp-for="LastName" class="form-control", disabled="disabled"/>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="UserId" class="form-control" />
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="MainMail" class="form-control" />
            </div>
            <div class="form-group">
                <input type="hidden" class="form-check-input" asp-for="ProfileCreated" />
            </div>
            <div class="form-group">
                <label class="control-label">User Role</label>
                @Html.DropDownListFor(model => model.UserRoleId, new SelectList(Model.UserRoles), new { @class = "form-control btn btn-outline-dark dropdown-toggle" })
                <span asp-validation-for="UserRoleId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="CountAdminRole" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a class="btn btn-dark" asp-action="Index">Back to Budget Users</a>
            </div>
        </form>
    </div>
</div>

BudgetPlannerMVC.Web/Views/BudgetUser/Index.cshtml
@model BudgetPlannerMVC.Application.ViewModels.UserView.ListBudgetUserForListVm

@{
    ViewData["Title"] = "Index";
}

<h1 class="display-4">Budget Users</h1>
@if (User.IsInRole("PreUser"))
{
    <p>
        <a class="btn btn-primary" asp-action="CreateBudgetUserProfile" style="margin-top: 10px">Create Profile</a>
    </p>
}
<form asp-action="Index" asp-controller="BudgetUser" method="post" style="margin-bottom:60px">
    <div class="form-inline justify-content-start">
        <div class="d-flex" style="margin:10px 20px 20px 0px">
            <div class="d-flex">
                <input class="form-control form-rounded" type="text" asp-for="SearchString" name="searchString" id="searchString" placeholder="Search" />
            </div>
            <div class="d-flex">
                <input class="btn btn-outline-dark ml-2" type="submit" value="Search" />
            </div>
        </div>
    </div>
    <div class="row">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        User Name
                    </th>
                    <th>
                        Last Name
                    </th>
                    <th>
                        First Name
                    </th>
                    <th>
                        Role
                    </th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.BudgetUsers)
                {
                    @if (!(item.UserId == Model.CurrentUserId && User.IsInRole("PreUser")))
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.UserName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.LastName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FirstName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.UserRoleId)
                            </td>
                            @if (User.IsInRole("Admin"))
                            {
                                <td>
                                    @Html.ActionLink("Edit", "EditBudgetUser", new {  id=item.Id }, new {@class = "btn btn-info"})
                                    @Html.ActionLink("Details", "Details", new { id=item.Id}, new {@class = "btn btn-warning"})
                                    @if (item.UserRoleId == "Admin")
                                    {
                                        @Html.ActionLink("Delete", "Delete", new {  id=item.Id }, new {@class = "btn btn-danger disabled"})
                                    }
                                    else
                                    {
                                        @Html.ActionLink("Delete", "Delete", new {  id=item.Id }, new {@class = "btn btn-danger"})
                                    }
                                    
                                </td>
                                @if (item.UserId == Model.CurrentUserId && Model.CountAdminUsers <= 1)
                                {
                                    <td>
                                        @Html.ActionLink("User permissions", "EditUserRole", new {  userId=item.UserId }, new {@class = "btn btn-primary disabled"})
                                    </td>
                                }
                                else
                                {
                                    <td>
                                        @Html.ActionLink("User permissions", "EditUserRole", new {  userId=item.UserId }, new {@class = "btn btn-primary"})
                                    </td>
                                }

                            }
                            else if (item.UserId == Model.CurrentUserId && User.IsInRole("User"))
                            {
                                <td>
                                    @Html.ActionLink("Edit", "EditBudgetUser", new {  id=item.Id }, new {@class = "btn btn-info"})
                                    @Html.ActionLink("Details", "Details", new { id=item.Id}, new {@class = "btn btn-warning"})
                                </td>
                                <td></td>
                            }
                            else
                            {
                                <td>
                                    @Html.ActionLink("Edit", "EditBudgetUser", new {  id=item.Id }, new {@class = "btn btn-info disabled"})
                                    @Html.ActionLink("Details", "Details", new { id=item.Id}, new {@class = "btn btn-warning"})
                                </td>
                                <td></td>
                            }
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
    <div class="row">
        <table>
            <tr>
                @for (int i = 1; i <= Math.Ceiling(Model.Count / (double)Model.PageSize); i++)
                {
                    <td>
                        @if (i != Model.CurrentPage)
                        {
                            <a class="badge badge-dark" href="javascript:PagerClick(@i)">@i</a>
                        }
                        else
                        {
                            <span class="badge badge-outline-dark">@i</span>
                        }
                    </td>
                }
            </tr>
        </table>
        <input type="hidden" name="pageNo" id="pageNo" />
        <input type="hidden" name="pageSize" id="pageSize" value="8" />
    </div>
</form>

@section Scripts
{
<script type="text/javascript">
    function PagerClick(index)
    {
        document.getElementById("pageNo").value = index;
        document.forms[1].submit();
    }
</script>
}